### ISSUE TITLE
ido-clever-match not listed on MELPA?

### ISSUE THREAD

**Issue by ReneFroger** [Bogdanp/ido-clever-match#2]
Thanks for sharing this package! However, I couldn't find it on MELPA. 
Could this perhaps be listed on MELPA?

Thanks in advance!

**Comment by Bogdanp** [comment]
I opened a PR on the MELPA repo this morning: https://github.com/milkypostman/melpa/pull/3191 . It'll be up once the maintainers of MELPA approve it :)

**Comment by Bogdanp** [comment]
The PR has been merged and the package will be up on MELPA shortly!
